const { exec } = require('child_process')
const event = require('./functions/fm_crawler/event.json')

const allCourses = [
  'advanced-react-patterns',
  'sql-fundamentals',
  'content-strategy',
  'web-performance',
  'computer-science-2',
  'js-fundamentals-functional-v2',
  'git-in-depth',
  'full-stack-v2',
  'api-node-rest-graphql',
  'building-apps-angular',
  'typescript',
  'css-in-depth-v2',
  'css-grids-flexbox',
  'javascript-hard-parts',
  'advanced-vue',
  'visual-studio-code',
  'web-security',
  'react-state',
  'javascript-wordpress',
  'progressive-web-apps',
  'vue',
  'advanced-async-js',
  'testing-modular-front-end',
  'leveldb-crypto',
  'networking-streams',
  'bash-vim-regex',
  'functional-javascript-v2',
  'javascript-foundations',
  'linting-asts',
  'react',
  'testing-javascript',
  'modern-seo',
  'sass',
  'debugging-javascript',
  'd3-v4',
  'hapi-js',
  'firebase-react',
  'data-structures-algorithms',
  'advanced-ember-2',
  'full-stack',
  'electron',
  'secure-auth-jwt',
  'reactive-angular',
  'web-apps-angular-2',
  'complete-intro-react',
  'web-accessibility',
  'elm',
  'es6-right-parts',
  'production-node-aws',
  'open-source',
  'webpack',
  'react-native',
  'chrome-dev-tools',
  'motion-design-css',
  'react-intro',
  'computer-science',
  'good-parts-javascript-web',
  'reactive-angular-2',
  'angular-2',
  'rethinking-async-js',
  'functional-js-lite',
  'svg-animation',
  'ember-2',
  'api-design-nodejs',
  'angular-components-es6',
  'modern-web-apps',
  'meteor',
  'unit-testing-javascript',
  'asynchronous-javascript',
  'organizing-javascript',
  'javascript-coercion',
  'javascript-basics',
  'ui-prototyping-framer',
  'angular-app-dev',
  'react-intro-to-flux',
  'responsive-email',
  'javascript-jquery-dom',
  'smacss',
  'js-fundamentals-to-functional',
  'jsnext-es6',
  'responsive-typography',
  'web-development',
  'javascript-frameworks-showdown',
  'functional-javascript',
  'realtime-html5-nodejs',
  'advanced-javascript',
  'html5-media-apis',
  'workflows-and-tooling',
  'interactive-data-visualization-d3-js',
  'angularjs-in-depth',
  'backbone-js-in-depth-testing-mocha-sinon',
  'css3-in-depth',
  'web-ui-architecture',
  'lean-front-end-engineering',
  'responsive-web-design',
  'website-performance',
  'javascript-the-good-parts',
  'angularjs-and-code-testability',
  'introduction-html5-css3',
  'jquery-plugins-jquery-ui',
  'jquery-in-depth',
  'introduction-to-javascript-jquery'
]

allCourses.forEach(courseId =>
  exec(
    `echo '${JSON.stringify({
      ...event,
      courseId
    })}' | apex invoke fm_crawler &`,
    (error, stdout, stderr) => {
      if (error) {
        console.error(`exec error: ${error}`)
        return
      }

      console.log(`stdout: ${stdout}`)
      console.log(`stderr: ${stderr}`)
    }
  )
)
